<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSFER</name>
   <tag></tag>
   <elementGuidId>adc115e9-af4d-4317-b2a3-94485353b213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>292fa535-31fa-461a-bb4e-d9ed25623f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>604d2e07-3e32-4bce-ae3f-3f38a24b1a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>1727cf30-5e24-42fa-8349-0d7f3a85f165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>1c9a982e-8d4e-4865-97a5-755ee79f0003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>9725d7bc-652d-43a1-bb5c-d2b262191a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY'])[1]/following::div[3]</value>
      <webElementGuid>8cc70952-8fa2-4f11-b6c4-77198c9cc7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELOAD'])[1]/preceding::div[1]</value>
      <webElementGuid>aa0b663a-a347-4209-a6f8-80bf6777098d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REQUEST'])[1]/preceding::div[4]</value>
      <webElementGuid>4274ed29-dc0e-4439-a08a-bbeb3868c03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSFER']/parent::*</value>
      <webElementGuid>edb204be-6e48-458e-b879-6a59a6eac523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>ab60a052-269d-42f7-afd9-af0d60e5a713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TRANSFER' or . = 'TRANSFER')]</value>
      <webElementGuid>7b4068ae-45da-45ca-aaa2-1af82329bf50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
