<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6988a447-97c9-4055-a67a-0f111030834a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer-items']/div[2]/div/div/ul/li[6]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1606fe94-7006-4cf5-934d-cae82a2d4488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/teamsite/images/two_credit_cards.svg</value>
      <webElementGuid>8a7bd0b8-39ce-46b4-b8a0-c5ca088a097b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-items&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/ul[1]/li[6]/a[1]/img[1]</value>
      <webElementGuid>8737d925-44b3-4373-a969-5b0cc2e39e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer-items']/div[2]/div/div/ul/li[6]/a/img</value>
      <webElementGuid>db21621e-18e6-4e89-89b5-ddadb5b45fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/img</value>
      <webElementGuid>cb8767f3-8438-4d87-a8d1-c38f563c38e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/teamsite/images/two_credit_cards.svg']</value>
      <webElementGuid>ab13873f-45cb-45d9-a4af-d9111e9fe3aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
