<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Secure Verification</name>
   <tag></tag>
   <elementGuidId>b14e5c0a-8a4d-4be4-b84a-44c2a88920e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollToTransactions > div.Transactions---container---3sqaa > div.Transactions---content---2P7lC > div.Transactions---withSide---2taIP.container-fluid.Transactions---summaryContainer---1rNvj.undefined > div.row > div.col-xs-12 > div.Transactions---stickyConfirmation---2aISx > div > div.Confirm---confirm-wrapper---2INeM.Confirm---slide---3C7mA.put-in-modal > div.container-fluid > div.row > div.col-md-8.col-xs-12 > div.Confirm---confirm-right-wrapper---1xhcG > div > div.col-sm-4.col-xs-12 > div.Confirm---secure2uSection---3A7pq > div.hidden-xs > div.RenderDesktopDropdown---container---1CES2.Confirm---containerClass---xTcuc > div.dropdown.btn-group > #004</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='004'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d6f994e-a52a-49f2-96b7-0dbfa0e6fc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>004</value>
      <webElementGuid>a47f8333-e44b-46b6-91eb-1e3f508128ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af29a4ff-ddc7-4290-87af-685947a05256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>314c8da9-7132-495d-bdc2-061ec84c7a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85c0a221-c7a3-4a05-afec-5f2de1ec43cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9bfa779a-8a8d-4026-890b-d408cfb2f661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-default</value>
      <webElementGuid>c05581dd-4454-4d25-b726-2773f3115322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secure Verification</value>
      <webElementGuid>8541d7f1-d5a3-49e1-bae4-7189ad34a09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[@class=&quot;Transactions---content---2P7lC&quot;]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;Transactions---stickyConfirmation---2aISx&quot;]/div[1]/div[@class=&quot;Confirm---confirm-wrapper---2INeM Confirm---slide---3C7mA put-in-modal&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-xs-12&quot;]/div[@class=&quot;Confirm---confirm-right-wrapper---1xhcG&quot;]/div[1]/div[@class=&quot;col-sm-4 col-xs-12&quot;]/div[@class=&quot;Confirm---secure2uSection---3A7pq&quot;]/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;RenderDesktopDropdown---container---1CES2 Confirm---containerClass---xTcuc&quot;]/div[@class=&quot;dropdown btn-group&quot;]/button[@id=&quot;004&quot;]</value>
      <webElementGuid>7768777b-4ee2-4400-b98d-2e737f0ce764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='004'])[2]</value>
      <webElementGuid>4c66aa86-ff83-47e0-b2e2-8467d16b27c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>2f1d4eca-a8dc-4955-af4c-7ca63d7e675d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Verification'])[1]/following::button[1]</value>
      <webElementGuid>92fa833d-3a0e-4c57-8b01-3a76a9d57004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download the MAE app and activate Secure2u to authorise your transactions.'])[1]/following::button[2]</value>
      <webElementGuid>a60b2913-8b2a-478f-8862-86da2baa4542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Verification'])[4]/preceding::button[1]</value>
      <webElementGuid>fddfbe3f-1f2a-4707-90ea-840fadb4f5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>796c391a-3f2c-49f6-9c89-ad29b10d2847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '004' and @type = 'button' and (text() = 'Secure Verification' or . = 'Secure Verification')]</value>
      <webElementGuid>03e7b4fe-d3cd-4c5c-be42-f901a6292cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
