<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recipient Reference_transferPurpose</name>
   <tag></tag>
   <elementGuidId>c21a0306-cef1-4876-8882-68313350a76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferPurpose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferPurpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>758ae75e-b7e9-4177-adb6-564f3399a6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>42df9e5d-42c6-496c-b917-f5029677595a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61fb6f4b-469a-41e5-9f30-da34204f4947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>79f5c6e3-9c74-486b-9c3c-a26e07ad2b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferPurpose</value>
      <webElementGuid>65ac3546-3840-43ac-ba59-40e17ce9edd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Recipient Reference</value>
      <webElementGuid>13527b0c-1992-4570-907d-4609597c4f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferPurpose&quot;)</value>
      <webElementGuid>acacd5c6-2545-4d62-a185-60ebef4cd9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferPurpose']</value>
      <webElementGuid>15eb7691-028e-4f72-a495-e2e93a27363d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>3fc6ab69-88a9-4340-bf3b-fa1d41b6b27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>072cec49-cf92-443a-a7ee-dc18d9968886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'transferPurpose' and @title = 'Please Enter a Valid Recipient Reference']</value>
      <webElementGuid>7ef8e92b-c7da-426d-8456-65a6c3abd4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
