<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4804104a-bd75-4c7f-aff7-8423a26b896c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer-items']/div[2]/div/div/ul/li[6]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>30251a03-06ad-4602-b57a-08266bdd08df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/teamsite/images/two_credit_cards.svg</value>
      <webElementGuid>d8076163-a112-4b37-ac0f-9fb8f05ccbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-items&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/ul[1]/li[6]/a[1]/img[1]</value>
      <webElementGuid>3646b96c-716a-4eef-88f2-b7af3050ab8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer-items']/div[2]/div/div/ul/li[6]/a/img</value>
      <webElementGuid>c319a739-b94d-4e75-be79-f06a918360ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/img</value>
      <webElementGuid>10a7f040-d6c8-40c5-af96-fa74db819620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/teamsite/images/two_credit_cards.svg']</value>
      <webElementGuid>8223c879-7f67-4659-80bf-0f7559bb2b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
