<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NRIC Number_proxyId</name>
   <tag></tag>
   <elementGuidId>22532029-79f5-442b-83a3-a1ed39ea5b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proxyId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proxyId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11dc5329-5b16-4eda-b949-001f891fc47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>2c8ae9fc-c113-497c-a83c-238ab9069aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81529321-4738-4b5c-ba52-0fcc442a037f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e83d6108-56c0-455b-9f52-3a3aca0693dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proxyId</value>
      <webElementGuid>54140a0c-e37d-4066-98da-0eeb2ce203d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid NRIC Number</value>
      <webElementGuid>2a4f4f6e-0359-4e9b-8097-5a04021c73cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proxyId&quot;)</value>
      <webElementGuid>7183dcf3-ff0f-4905-a66d-bf88ab953dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proxyId']</value>
      <webElementGuid>46ed1ca1-81d6-4539-b843-8fae16652532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>a6a39a36-6018-4668-8bb3-ddc0144f77cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>be4ce647-902a-4ad7-8ada-7c76f1c0f810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'proxyId' and @title = 'Please Enter a Valid NRIC Number']</value>
      <webElementGuid>3617ff06-d546-4a5e-8e20-8d7c05053cb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
