<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logout_first image</name>
   <tag></tag>
   <elementGuidId>8dfcb0b6-3d95-47f2-8807-0f0e310cf199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='post-logout-banner-1']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#post-logout-banner-1 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.maybank.com/iwov-resources/images/Logout/lazada111121.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;core---childContainer---2GFqG container-fluid&quot;]/div[@class=&quot;Logout---container---1hHAm row&quot;]/div[@class=&quot;loaderParent&quot;]/div[@class=&quot;loaderChildren&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-10 col-sm-8 col-xs-8 ZeroActivities---zero_activities_container---27J7s&quot;]/div[@class=&quot;row hidden-sm hidden-xs&quot;]/div[1]/div[1]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;ZeroActivities---blurb---1sof6&quot;]/a[@id=&quot;post-logout-banner-1&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='post-logout-banner-1']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.maybank.com/iwov-resources/images/Logout/lazada111121.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
