<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter Password</name>
   <tag></tag>
   <elementGuidId>b81888b0-9be2-40d3-aa8e-c597476f32ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-password-input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'my-password-input']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3adaf444-65e6-48fe-a06c-443d5a2f5ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d131d42-774f-46da-a55e-f5fb16a94af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>My Password</value>
      <webElementGuid>4b19b293-1843-40cb-8e97-2f2bd62b3fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my-password-input</value>
      <webElementGuid>cffaca66-ee4d-47cd-9e18-b4faacd928cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SecurityPhrase---login-input---AwPq0 SecurityPhrase---login-input-font---14Asi</value>
      <webElementGuid>236a77ff-3060-4a49-935e-afbe123aa3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>my-guid</name>
      <type>Main</type>
      <value>738e8f5b-23b8-4703-9ae6-d213806b048d</value>
      <webElementGuid>303ee7ef-c9e4-4cfd-ac92-bee9219c91cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e9169852-6ab1-418d-bec5-7a5348b2817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14514b7a-c5ad-4180-bc11-7571d52712e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c445d10-835f-40ba-8357-2301ea80da51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aac61d46-60c2-4721-ba3c-30dc30886227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-password-input&quot;)</value>
      <webElementGuid>b981351c-3924-4ff1-9b5e-f5bd48cda794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my-password-input']</value>
      <webElementGuid>8f899a82-b88b-4a33-8e62-0cf37dd980b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>078c81a8-12e3-4c79-b685-82db6e56b3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9d104ba6-16a9-40c9-95cb-35277170c36c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
