<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Own Accounts</name>
   <tag></tag>
   <elementGuidId>0fca6859-c02c-49cc-8f73-5c1cb5d7fa72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.RenderDesktopDropdown---container---26t5v.PayFromToContainer---containerClass---m7dvC > div.dropdown.btn-group > #payto_dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='payto_dropdown'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f6ad44f-bfbd-4710-a246-3506f8db2b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payto_dropdown</value>
      <webElementGuid>1f88871f-5647-4e25-87a2-8f81396a3711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00d19086-106f-4d4f-9f8d-4d448c13c5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1ba0217-f104-4930-b5fa-b0c7b12b85f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cf27e80-55d3-4e4b-b64c-54e8ec00ea5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2066ebce-bd63-4031-9779-2a284aca64e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-default</value>
      <webElementGuid>6bb803ba-9fc8-431a-997c-9dd795aba637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Own Accounts </value>
      <webElementGuid>632352c4-a59b-4e48-9721-c21008590cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---1wLDZ&quot;]/div[1]/div[@class=&quot;Transactions---withSide---8AF6d container-fluid Transactions---summaryContainer---2cBfk&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[2]/div[@class=&quot;Transactions---backgroundTile---1MSOI&quot;]/div[@class=&quot;Transactions---paddingContent---15RoA&quot;]/div[@class=&quot;row PayFromToContainer---payFromToContainer---1HhaN&quot;]/div[@class=&quot;col-xs-12 col-lg-8 col-md-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;hidden-xs col-sm-10 col-xs-12 PayFromToContainer---dropdownHolder---2tkrl&quot;]/div[@class=&quot;RenderDesktopDropdown---container---26t5v PayFromToContainer---containerClass---m7dvC&quot;]/div[@class=&quot;dropdown btn-group&quot;]/button[@id=&quot;payto_dropdown&quot;]</value>
      <webElementGuid>85a10ca7-f58e-480d-b6af-58488382a99d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='payto_dropdown'])[2]</value>
      <webElementGuid>3f7892f1-5108-4b29-a000-75f314580948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div/div/button</value>
      <webElementGuid>c0df7740-76cb-49e0-84fa-ce98ad68a86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASNB Accounts'])[1]/following::button[1]</value>
      <webElementGuid>8d499275-2f45-4caf-a82a-fc045159724f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/following::button[1]</value>
      <webElementGuid>5b2ef902-e6ca-437f-a06a-50877452c755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Own Accounts'])[4]/preceding::button[1]</value>
      <webElementGuid>6ea2dc77-5567-4677-ba15-8c3b334c57ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/button</value>
      <webElementGuid>7a54d19b-74d3-4505-a528-2cc3dd379630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payto_dropdown' and @type = 'button' and (text() = 'Own Accounts ' or . = 'Own Accounts ')]</value>
      <webElementGuid>64fb09cb-4512-4f09-8cc6-fb02e6836901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
