<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSFER</name>
   <tag></tag>
   <elementGuidId>f041f5c5-d614-4e4e-928f-4c9b76531ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a599adcd-1850-4db1-8e4c-7b5e6f454d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>8d4dce7b-ddd6-4669-9e4f-b50f1b7789c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>6e155468-cd5a-4929-af40-f2b59e5f3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>8254e878-fb1a-4d88-a188-981b20a7b6dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>01807e59-0394-4594-9250-8269ef65c35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY'])[1]/following::div[3]</value>
      <webElementGuid>e9379b6c-77fa-4de9-a031-f18a82aa9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELOAD'])[1]/preceding::div[1]</value>
      <webElementGuid>56c088d4-7034-42a8-ac70-03d02542fa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REQUEST'])[1]/preceding::div[4]</value>
      <webElementGuid>15773f0f-fef5-47f9-b980-5701a39c118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSFER']/parent::*</value>
      <webElementGuid>23c0596f-869e-48b7-b935-bff3f779da16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>98a1296c-d5c8-431b-be5a-59e08660300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TRANSFER' or . = 'TRANSFER')]</value>
      <webElementGuid>93645714-06c5-46a6-99bf-715789bec3f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
