<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Interbank GIRO</name>
   <tag></tag>
   <elementGuidId>842ca952-803a-4d4e-a78b-19b800557921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > div.TransferModal---selectedItem---31Inz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div/div[4]/div/div[2]/div[2]/div/div/ul/li[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8bcbd75-6a2e-4765-bd12-f1e5b6d07fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---selectedItem---31Inz</value>
      <webElementGuid>444e7d4a-634a-4371-9322-0a4ad4e970dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interbank GIRO</value>
      <webElementGuid>add1dd2a-52ac-4872-adcd-f8df2e9c45dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[1]/div[@class=&quot;GeneralModal---container---2eNZL undefined&quot;]/div[@class=&quot;GeneralModal---modal---3S0wp TransferModal---container---30sqf TransferModal---withNote---RCB-A&quot;]/div[@class=&quot;modal-dialog GeneralModal---animated---3rWCl GeneralModal---slideInDown---QgFoz&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;undefined modal-body&quot;]/div[@class=&quot;TransferModal---whitebg---3wCdG&quot;]/div[@class=&quot;TransferModal---recipientWrapper---1JmtN&quot;]/div[4]/div[@class=&quot;row TransferModal---inputPair---1VxR1&quot;]/div[@class=&quot;col-sm-7&quot;]/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;RenderDesktopDropdown---container---26t5v TransferModal---containerClass---11ho5&quot;]/div[@class=&quot;dropdown open btn-group&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[2]/a[1]/div[@class=&quot;TransferModal---selectedItem---31Inz&quot;]</value>
      <webElementGuid>c66e867b-c54c-4cfa-8dd1-51ab10223120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div/div[4]/div/div[2]/div[2]/div/div/ul/li[2]/a/div</value>
      <webElementGuid>7d7a6601-1845-47af-af27-0be7ca886f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DuitNow Transfer'])[4]/following::div[1]</value>
      <webElementGuid>979d75c2-ad5c-429f-b496-b4517f1f0e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DuitNow Transfer'])[3]/following::div[2]</value>
      <webElementGuid>469c540c-9655-4ab9-8e65-fd7a53631a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Amount'])[1]/preceding::div[1]</value>
      <webElementGuid>ca6ff42d-50e3-4289-903c-06e6462d72ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a/div</value>
      <webElementGuid>1f98c326-21ae-446b-8893-2405802d7080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Interbank GIRO' or . = 'Interbank GIRO')]</value>
      <webElementGuid>cca8799d-ebc5-4ee7-8873-15ed061e3bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
