<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recipient Reference_transactionReferenceNo</name>
   <tag></tag>
   <elementGuidId>d9f19b56-061a-4d43-adec-3f386398eb8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transactionReferenceNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transactionReferenceNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cff83cc-5f02-4cac-8232-1486e959869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>a97cb2b4-81db-488a-a0bf-7c959bb50179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f74f22d4-5613-4bb6-b3ef-7be3f6729e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>75411cdd-3e70-493e-ab43-4c081d1dbbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transactionReferenceNo</value>
      <webElementGuid>dabae800-1be4-4434-a5ff-5a3ff9d51421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Recipient Reference</value>
      <webElementGuid>86c1f01c-de0e-4a9e-b8e4-282b14d795f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionReferenceNo&quot;)</value>
      <webElementGuid>e7c72d5d-10bf-44d0-a22f-57246ac15eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transactionReferenceNo']</value>
      <webElementGuid>7a653303-7d94-4d18-9912-8cc3ce4ea038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>37228770-9c7b-4368-8863-1040d93cdd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>8f2cb9c8-e7cd-4950-b691-e4ecf3f5a988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'transactionReferenceNo' and @title = 'Please Enter a Valid Recipient Reference']</value>
      <webElementGuid>80f02de1-0ab6-414c-b156-838220b63f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
