<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Recipient, , s Name)_beneficiaryName</name>
   <tag></tag>
   <elementGuidId>8af0b701-8cc7-4152-ba7e-4ed24f94247a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaryName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaryName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57a8c26a-7cea-428b-a7ba-f24c9641936b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>d8fdd1c4-35ce-4c86-a8b6-a5b37e9f2ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60c27a81-0c1a-43d9-af18-5239d41cf476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>3c40f73d-cfb0-4a38-99bb-8a1f877de370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaryName</value>
      <webElementGuid>62b94e01-9f4c-42de-909a-3d6071f835f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Recipient's Name</value>
      <webElementGuid>32c74681-1a3f-4b99-85aa-5b65faf2b0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaryName&quot;)</value>
      <webElementGuid>05e0c90c-84b3-4f69-8693-19f489867ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaryName']</value>
      <webElementGuid>6d866dc6-6433-4602-babe-81523f0f7550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>de4e5e92-e3eb-4b85-a36f-b384daeaea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>a5ad9d81-a384-4aee-8e69-51882ed76f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'beneficiaryName' and @title = concat(&quot;Please Enter a Valid Recipient&quot; , &quot;'&quot; , &quot;s Name&quot;)]</value>
      <webElementGuid>498bdf72-a563-4251-ac49-3b6010f6b735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
