<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DuitNow Transfer</name>
   <tag></tag>
   <elementGuidId>49361377-0ab4-4429-8a04-7bd0a50d3c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.RenderDesktopDropdown---clsTitle---1A7S9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='transferType']/span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8457469-d138-4ae5-acdc-822a82661006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RenderDesktopDropdown---clsTitle---1A7S9</value>
      <webElementGuid>2fab0474-720a-4a56-960f-c833ff186d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DuitNow Transfer</value>
      <webElementGuid>5a098c96-fcb3-488e-95e3-563d159bd663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[1]/div[@class=&quot;GeneralModal---container---2eNZL undefined&quot;]/div[@class=&quot;GeneralModal---modal---3S0wp TransferModal---container---30sqf TransferModal---withNote---RCB-A&quot;]/div[@class=&quot;modal-dialog GeneralModal---animated---3rWCl GeneralModal---slideInDown---QgFoz&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;undefined modal-body&quot;]/div[@class=&quot;TransferModal---whitebg---3wCdG&quot;]/div[@class=&quot;TransferModal---recipientWrapper---1JmtN&quot;]/div[4]/div[@class=&quot;row TransferModal---inputPair---1VxR1&quot;]/div[@class=&quot;col-sm-7&quot;]/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;RenderDesktopDropdown---container---26t5v TransferModal---containerClass---11ho5&quot;]/div[@class=&quot;dropdown btn-group&quot;]/button[@id=&quot;transferType&quot;]/span[@class=&quot;RenderDesktopDropdown---clsTitle---1A7S9&quot;]</value>
      <webElementGuid>e61d7a8a-08cd-439c-857d-bcb4d087b206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='transferType']/span)[2]</value>
      <webElementGuid>fa27e89c-2bf6-47d0-94e4-8bd181c7092f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DuitNow Transfer'])[1]/following::span[1]</value>
      <webElementGuid>4421a295-ed06-42eb-9a66-fd2b3a23d75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Mode'])[1]/following::span[4]</value>
      <webElementGuid>d910f8ed-b5b3-4220-b0ab-8a2e3f5c825a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DuitNow Transfer'])[4]/preceding::span[2]</value>
      <webElementGuid>dbd631cf-6896-430c-aad5-116d66ee1779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>1e000c45-70ea-418b-a412-a594ed8618af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DuitNow Transfer' or . = 'DuitNow Transfer')]</value>
      <webElementGuid>ee7c562b-9ea3-4c74-9db1-d3d7e5f5d615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
