<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transaction Accepted</name>
   <tag></tag>
   <elementGuidId>e6c4e2a8-58e1-4248-a943-1bfa5aa3c3f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.SaveReceiptNewPayment---headerMsg---35lPi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40ebc187-2ad2-4e8e-924f-3b41c1ed8071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SaveReceiptNewPayment---headerMsg---35lPi</value>
      <webElementGuid>be631203-1ea9-41bc-a12a-be1f58e2e6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction Accepted</value>
      <webElementGuid>c09947bc-7362-4084-b167-a54b19352fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[@class=&quot;Transactions---content---2P7lC&quot;]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;Transactions---stickyConfirmation---2aISx&quot;]/div[1]/div[1]/div[@class=&quot;SaveReceiptNewPayment---saveWrapper---3Q7bZ put-in-modal SaveReceiptNewPayment---slide---2j_l8&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-xs-12&quot;]/div[@class=&quot;SaveReceiptNewPayment---save-right-wrapper---2KHN9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-xs-12&quot;]/div[@class=&quot;SaveReceiptNewPayment---save-heading-wrapper-dashboard---2NF4n&quot;]/div[1]/span[@class=&quot;SaveReceiptNewPayment---headerMsg---35lPi&quot;]</value>
      <webElementGuid>399ff781-f1a3-4683-9a85-92e1c5b2a458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div/span</value>
      <webElementGuid>a937ef7b-96d3-4213-bc55-28a4f4a43926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed on Tuesday 30 July 2024 at 15:17:41'])[1]/following::span[1]</value>
      <webElementGuid>735e9e44-5739-4130-ae2b-f34a55ed4ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 1.00'])[2]/following::span[1]</value>
      <webElementGuid>feb96041-0bf6-4c64-b1df-1e0fb7970612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Transfer'])[1]/preceding::span[2]</value>
      <webElementGuid>14ec092d-fba6-4661-8fe6-a76314328c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transaction Accepted']/parent::*</value>
      <webElementGuid>4089c4a2-2f72-4a39-a1e4-7d933ea2904b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div/span</value>
      <webElementGuid>d76197c9-9e4b-4441-834e-1143691b21b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction Accepted' or . = 'Transaction Accepted')]</value>
      <webElementGuid>adf4bacc-3941-4412-a76d-c631a2f0b173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
