<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSFER</name>
   <tag></tag>
   <elementGuidId>4d065175-d3e3-4944-810c-e61e656cafd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71979eac-4f19-401b-93bc-e7e47a33e042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>85d3c343-4d39-49d4-9dd8-1da9c745d04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>a9224406-4ac6-4539-b02a-65c895bd2c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>4bb54396-dc54-4bbd-a961-34bbe4c614ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>96c084f1-85e0-47ae-8116-2afa2d20437d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY'])[1]/following::div[3]</value>
      <webElementGuid>792201d1-7c33-4333-95fe-d327d10cd67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELOAD'])[1]/preceding::div[1]</value>
      <webElementGuid>4c2c1658-f732-41ba-9564-d90d451b8cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REQUEST'])[1]/preceding::div[4]</value>
      <webElementGuid>dc1b3451-c11a-4278-a3e6-85f685a6fa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSFER']/parent::*</value>
      <webElementGuid>355dde9f-acae-4878-9d04-90f336dee49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>ec24ef03-0d0f-49f7-91d1-40fb1ccfdb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TRANSFER' or . = 'TRANSFER')]</value>
      <webElementGuid>1e82ba9b-094d-4a5a-8358-1d5988bc8143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
