<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Secure Verification</name>
   <tag></tag>
   <elementGuidId>26221570-2377-4039-94ff-ea2e4a56d0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scrollToTransactions > div.Transactions---container---3sqaa > div.Transactions---content---2P7lC > div.Transactions---withSide---2taIP.container-fluid.Transactions---summaryContainer---1rNvj.undefined > div.row > div.col-xs-12 > div.Transactions---stickyConfirmation---2aISx > div > div.Confirm---confirm-wrapper---2INeM.Confirm---slide---3C7mA.put-in-modal > div.container-fluid > div.row > div.col-md-8.col-xs-12 > div.Confirm---confirm-right-wrapper---1xhcG > div > div.col-sm-4.col-xs-12 > div.Confirm---secure2uSection---3A7pq > div.hidden-xs > div.RenderDesktopDropdown---container---1CES2.Confirm---containerClass---xTcuc > div.dropdown.btn-group > #004</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='004'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b6174ee-be03-4158-8462-78c922b7a964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>004</value>
      <webElementGuid>4ab89ac8-971f-4a42-8ffd-c881b9fbf992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>046b53a3-34af-403d-8a38-a9bf6c827015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d36e9191-2f12-439b-a544-5c44b1d99341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22db4ef1-20e6-4fbd-9ef5-7298d7c67166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e691534-3570-43ff-a7ba-22021ef0a191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-default</value>
      <webElementGuid>aa1cfc4b-26dc-49ea-b3ca-e33c7b913ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secure Verification</value>
      <webElementGuid>9b35c31a-5d21-452d-8f05-c11d74e0db67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[@class=&quot;Transactions---content---2P7lC&quot;]/div[@class=&quot;Transactions---withSide---2taIP container-fluid Transactions---summaryContainer---1rNvj undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;Transactions---stickyConfirmation---2aISx&quot;]/div[1]/div[@class=&quot;Confirm---confirm-wrapper---2INeM Confirm---slide---3C7mA put-in-modal&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-xs-12&quot;]/div[@class=&quot;Confirm---confirm-right-wrapper---1xhcG&quot;]/div[1]/div[@class=&quot;col-sm-4 col-xs-12&quot;]/div[@class=&quot;Confirm---secure2uSection---3A7pq&quot;]/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;RenderDesktopDropdown---container---1CES2 Confirm---containerClass---xTcuc&quot;]/div[@class=&quot;dropdown btn-group&quot;]/button[@id=&quot;004&quot;]</value>
      <webElementGuid>5c739ed1-58c2-477a-80bc-0e3bfae21dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='004'])[2]</value>
      <webElementGuid>f7970f3c-9fab-4f54-a99d-b4b945723e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>13870133-bfbc-4cd7-a60e-92b9ed3d02af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Verification'])[1]/following::button[1]</value>
      <webElementGuid>d3b9d2ef-f0c4-48ae-b4be-bd208ad4a234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tap on the notification on your smartphone to approve the transaction.'])[1]/following::button[2]</value>
      <webElementGuid>e0b1745f-0c2f-4939-8352-3c2fed9f6efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Verification'])[4]/preceding::button[1]</value>
      <webElementGuid>b396d90e-469e-4147-9154-b17c7333977c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>ea8ac4c0-3042-4a68-981a-e9b8da61572c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '004' and @type = 'button' and (text() = 'Secure Verification' or . = 'Secure Verification')]</value>
      <webElementGuid>1262a910-82a1-4a90-9a3d-09810d0f931c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
