<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Own Accounts_lhc_needhelp_widget_v2</name>
   <tag></tag>
   <elementGuidId>dcba56bb-38da-4898-9cd6-ea0277bc3780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lhc_needhelp_widget_v2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lhc_needhelp_widget_v2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3dade75c-157e-45d3-b1e7-89af2123a970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lhc_needhelp_widget_v2</value>
      <webElementGuid>8af16912-4a2b-47df-95b3-cfa6349dc7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lhc-desktop</value>
      <webElementGuid>e34a9d62-8c29-429b-998f-674f88ad9e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lhc_needhelp_widget_v2&quot;)</value>
      <webElementGuid>aa98ae10-c3ba-44b5-8c95-b132a58609a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lhc_needhelp_widget_v2']</value>
      <webElementGuid>ef67091d-31b9-4cad-a286-1319aa5f5ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lhc_container_v2']/iframe[3]</value>
      <webElementGuid>5a1c20a7-3171-4ef6-a266-b75b9f302043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>1efbdee3-2e0d-4c96-9f6c-28cd16b33a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lhc_needhelp_widget_v2']</value>
      <webElementGuid>7b0ae0d1-ed22-49e4-9393-007503bc63c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
