<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e00dd421-e1b7-4226-ac6a-b2a8b07fa126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TransferModal---radioButton---1Wvx5 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div[6]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50f55b90-757e-4b9b-abb7-b8daca512d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icons/radio_button.svg</value>
      <webElementGuid>6f9d609d-79d3-459b-8130-4eb89a7998ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[1]/div[@class=&quot;GeneralModal---container---1MI-M undefined&quot;]/div[@class=&quot;GeneralModal---modal---2RPFr TransferModal---container---2JZnN TransferModal---withNote---23xqo&quot;]/div[@class=&quot;modal-dialog GeneralModal---animated---2vfJQ GeneralModal---slideInDown---3of__&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;undefined modal-body&quot;]/div[@class=&quot;TransferModal---whitebg---c-ZSZ&quot;]/div[@class=&quot;TransferModal---recipientWrapper---1B7n3&quot;]/div[1]/div[@class=&quot;row TransferModal---inputPair---2v4pK&quot;]/div[@class=&quot;col-xs-2 col-sm-1&quot;]/div[@class=&quot;TransferModal---radioButton---1Wvx5&quot;]/img[1]</value>
      <webElementGuid>f0cf2f6f-f9ee-4873-a65b-7da1381d2353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div[6]/div/div/div/div/img</value>
      <webElementGuid>f56d8084-fdd2-4127-b40b-2f33a96e7a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/img</value>
      <webElementGuid>aceb0785-ac2b-4f33-ac8d-83700b9610d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icons/radio_button.svg']</value>
      <webElementGuid>4f659b22-1f2d-4083-a0b0-8fe9cd592976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
