<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Didn, , t get the notification F_fe0af0</name>
   <tag></tag>
   <elementGuidId>d8e3e9df-a627-4cba-a670-4c7b8ee4c593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.OneTimePassword---imageBanner---39bx0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b344dff2-715a-4d85-9d7a-8e58fe7b0c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OneTimePassword---imageBanner---39bx0</value>
      <webElementGuid>34a6ebed-885e-44c0-9156-bc5a2ae69f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://172.31.11.35/iwov-resources/images/upload/s2u-steps-bar.png</value>
      <webElementGuid>ec1ee1b6-ba1f-42d2-9eda-3ba74467ab4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---1wLDZ&quot;]/div[@class=&quot;Transactions---content---3qHxP&quot;]/div[@class=&quot;Transactions---withSide---8AF6d container-fluid Transactions---summaryContainer---2cBfk undefined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;Transactions---stickyConfirmation---MY2KT&quot;]/div[1]/div[@class=&quot;OneTimePassword---otp-wrapper---2CDTn OneTimePassword---slide---3wKbJ put-in-modal&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-md-8 col-sm-12 col-xs-12&quot;]/div[@class=&quot;OneTimePassword---verification-content---eZA3t&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pull-left col-lg-7 col-md-7 col-sm-7 col-xs-7 OneTimePassword---imageContainer---2y0XL&quot;]/img[@class=&quot;OneTimePassword---imageBanner---39bx0&quot;]</value>
      <webElementGuid>1371eec2-802b-4fdd-8bf9-b13097f7b056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[3]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>823d5945-52ae-479a-95f7-109cc95e365c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://172.31.11.35/iwov-resources/images/upload/s2u-steps-bar.png')]</value>
      <webElementGuid>02863ddf-3694-41fd-a067-44080a0c670d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/img</value>
      <webElementGuid>7e5da74a-e33f-4ba8-bb74-f02e32e16d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://172.31.11.35/iwov-resources/images/upload/s2u-steps-bar.png']</value>
      <webElementGuid>e8f86a6d-d7e7-4cd3-a780-f043b72b1d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
