<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hello_my-password-input</name>
   <tag></tag>
   <elementGuidId>65f8c352-d629-437f-88b9-d96192258b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3befac5b-d305-456f-b48a-5fae82e798ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c31f689-d727-41d6-8d52-ea93fb7d92e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your password here</value>
      <webElementGuid>61da4957-67bf-482c-8b55-005cc2ba5d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my-password-input</value>
      <webElementGuid>3f9fe688-b167-4ded-bf4a-6ea32aaf2504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SecurityPhrase---login-input---AwPq0 SecurityPhrase---login-input-font---14Asi</value>
      <webElementGuid>fadf82ba-abd6-40d5-affe-1e6b68621214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>my-guid</name>
      <type>Main</type>
      <value>ed5038cc-5ea2-438b-983f-d19895e77d64</value>
      <webElementGuid>afe0f2af-ee2a-4616-b565-76944e1c8e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aba0777c-d2b4-4446-8a18-e727b1e679f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a488b3aa-5689-4c2d-bd12-ab18b9e2d08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e60b4a2c-a866-42b0-928f-e65db6f06aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f0be3ad-ce5d-4685-a19b-48b249c46233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1addeaa7-4a65-4afb-809c-34234d0a6c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-password-input&quot;)</value>
      <webElementGuid>d4b7cace-0a5b-400f-b718-73467030d065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my-password-input']</value>
      <webElementGuid>4b4b619f-948d-4aff-86f6-ea4627f813bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>6afb0fed-a835-4fbd-a6d5-9601aab3a9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2e680832-7b8a-46cd-9e5e-d3fd5666b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Input your password here' and @id = 'my-password-input']</value>
      <webElementGuid>80c4ddb2-3668-45de-b72e-d3c0756eb7fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
