<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport Number_proxyId</name>
   <tag></tag>
   <elementGuidId>b9c4bd26-1378-442a-b53c-8ddaa8113fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proxyId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proxyId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b962bf8-ddbf-4fe8-8e3b-5d6f1d3ef8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TransferModal---accountNumber---15nOE</value>
      <webElementGuid>028e917f-86f9-4148-978c-cb10767ebe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5805d8b4-bf63-4b48-b4fb-88adb20129f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>95b7a9cf-4989-4624-b51c-b714105276ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proxyId</value>
      <webElementGuid>2c5b0480-88be-40cb-b6e3-0447d9dfcace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Enter a Valid Passport Number</value>
      <webElementGuid>cbbbae63-135d-479b-9e61-05451d8ede22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proxyId&quot;)</value>
      <webElementGuid>d63e7c42-22b1-41c6-8e73-ee306b7caaed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proxyId']</value>
      <webElementGuid>fd335624-1e2d-4d45-8070-62956bf3aa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>aa30b564-ccdb-4e15-8b70-becd947b2382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>df176926-7998-453a-8121-070e5c6623c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'proxyId' and @title = 'Please Enter a Valid Passport Number']</value>
      <webElementGuid>41f74bea-87f7-4f83-9a25-d9015303a7b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
